// <auto-generated />
using BePart;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BePart.Migrations
{
    [DbContext(typeof(CatDbContext))]
    partial class CatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dtos.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Age")
                        .HasColumnType("float");

                    b.Property<string>("CatName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 3.5,
                            CatName = "Shadow",
                            Color = "Black",
                            Summary = "A stealthy little shadow that loves to sneak around."
                        },
                        new
                        {
                            Id = 2,
                            Age = 2.0,
                            CatName = "Snowball",
                            Color = "White",
                            Summary = "Fluffy and white as the fresh winter snow."
                        },
                        new
                        {
                            Id = 3,
                            Age = 4.0,
                            CatName = "Tiger",
                            Color = "Ginger",
                            Summary = "Loves to play and chase lasers."
                        },
                        new
                        {
                            Id = 4,
                            Age = 1.5,
                            CatName = "Smoky",
                            Color = "Grey",
                            Summary = "A curious explorer with a love for high places."
                        },
                        new
                        {
                            Id = 5,
                            Age = 7.0,
                            CatName = "Patch",
                            Color = "Calico",
                            Summary = "A wise old cat with a patchy coat and gentle eyes."
                        },
                        new
                        {
                            Id = 6,
                            Age = 0.80000000000000004,
                            CatName = "Biscuit",
                            Color = "Tabby",
                            Summary = "A playful kitten with endless energy and a penchant for mischief."
                        },
                        new
                        {
                            Id = 7,
                            Age = 3.0,
                            CatName = "Luna",
                            Color = "Siamese",
                            Summary = "Elegant and poised, with a mysterious aura and a melodious voice."
                        },
                        new
                        {
                            Id = 8,
                            Age = 2.5,
                            CatName = "Oreo",
                            Color = "Black and White",
                            Summary = "Sweet as a cookie, with a personality that's just as delightful."
                        },
                        new
                        {
                            Id = 9,
                            Age = 4.5,
                            CatName = "Simba",
                            Color = "Orange",
                            Summary = "Has the heart of a lion and enjoys basking in the sun."
                        },
                        new
                        {
                            Id = 10,
                            Age = 6.0,
                            CatName = "Sky",
                            Color = "Blue",
                            Summary = "A serene and peaceful presence, with a coat as soft as clouds."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
